name: 'p4_data_pipeline'
version: '1.0.0'
config-version: 2

profile: 'p4_data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  p4_data_pipeline:
    survey:
      +database: SURVEY_DATABASE
      +schema: SURVEY_SCHEMA
      staging:
        +materialized: view
        +snowflake_warehouse: P4_WAREHOUSE
      marts:
        +materialized: table
        +snowflake_warehouse: P4_WAREHOUSE

    stock:
      +database: STOCK_DB
      +schema: STOCK_SCHEMA
      staging:
        +materialized: view
        +snowflake_warehouse: P4_WAREHOUSE
      marts:
        +materialized: table
        +snowflake_warehouse: P4_WAREHOUSE
